name: MCU Setup Scripts Test

on:
  push:
    paths:
      - 'bootstrap_mcu_prereq.sh'
      - 'setup_mcu_env.sh'
      - '.github/workflows/test-mcu-setup.yml'
  pull_request:
    paths:
      - 'bootstrap_mcu_prereq.sh'
      - 'setup_mcu_env.sh'
  workflow_dispatch:

jobs:
  test-ubuntu-2404:
    name: Test on Ubuntu 24.04
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Make scripts executable
      run: |
        chmod +x bootstrap_mcu_prereq.sh
        chmod +x setup_mcu_env.sh
    
    - name: Run bootstrap script
      run: |
        export DEBIAN_FRONTEND=noninteractive
        export CI=true
        export GITHUB_ACTIONS=true
        ./bootstrap_mcu_prereq.sh
      timeout-minutes: 5
      
    - name: Run main setup script
      run: |
        export DEBIAN_FRONTEND=noninteractive
        export CI=true
        export GITHUB_ACTIONS=true
        ./setup_mcu_env.sh || {
          echo "=== エラーログの最後の50行 ==="
          tail -50 troubleshoot/*.log 2>/dev/null || echo "ログファイルが見つかりません"
          exit 1
        }
      timeout-minutes: 30
    
    - name: Verify installations
      run: |
        echo "=== Verification Results ==="
        echo "GCC: $(gcc --version | head -n1 || echo 'Not installed')"
        echo "Git: $(git --version || echo 'Not installed')"
        echo "CMake: $(cmake --version | head -n1 || echo 'Not installed')"
        echo "Python3: $(python3 --version || echo 'Not installed')"
        echo "ARM GCC: $(arm-none-eabi-gcc --version | head -n1 || echo 'Not installed')"
        echo "OpenOCD: $(which openocd &>/dev/null && echo "Installed at $(which openocd)" || echo 'Not installed')"
        
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: installation-logs
        path: troubleshoot/

  test-ubuntu-2204:
    name: Test on Ubuntu 22.04 (compatibility)
    runs-on: ubuntu-22.04
    continue-on-error: true
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Make scripts executable
      run: |
        chmod +x bootstrap_mcu_prereq.sh
        chmod +x setup_mcu_env.sh
    
    - name: Run scripts
      run: |
        ./bootstrap_mcu_prereq.sh
        ./setup_mcu_env.sh || true
        
    - name: Check results
      run: |
        echo "Compatibility test completed" 